services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      - mqtt_net
    restart: unless-stopped

  mqtt_logger:
    container_name: mqtt_logger
    build:
      context: .
    volumes:
      - ./:/code
    depends_on:
      mqtt:
        condition: service_started
      mariadb:
        condition: service_healthy
    networks:
      - mqtt_net
      - mqtt_db
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./config:/config
      - ./dump/:/docker-entrypoint-initdb.d
    networks:
      - mqtt_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    healthcheck:  # Add healthcheck for improved reliability
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mqtt_net:
    name: mqtt_net
  mqtt_db:
    name: mqtt_db
